### ISSUE TITLE
Few spanning reads extracted from BAM file

### ISSUE THREAD

**Issue by MaestSi** [arnederoeck/NanoSatellite#10]
Dear NanoSatellite developers,
I am testing the tool counting repeats of a 3bp-long repeat motif. In the BAM file I generated with Minimap2, 22 reads aligned on target. However, when running `Spanning_read_extractor.sh` only 3 spanning reads are extracted.
Is this a case where I should consider aligning reads following [your advice](https://github.com/mcfrith/last-rna/blob/master/last-long-reads.md)? Or, since I see reads correctly mapped in the BAM file, this is not the case?
Thank you.
Simone

**Comment by arnederoeck** [comment]
Hi Simone,
NanoSatellite requires reads which span the entire tandem repeat and they need to align to the left and right flank of the tandem repeat (and it's ok if the read is split in two over the tandem repeat by the aligner). I am assuming that while 22 reads may align to the tandem repeat, most of them probably align to only one side. Without seeing the data it is a bit difficult to figure out what is driving this. It could potentially be due to the aligner, but if for instance your reads are too short to span the entire tandem repeat then there is not much to do.

Best,
Arne

**Comment by MaestSi** [comment]
Hi Arne,
as you can see in the picture, the repeat of interest is in the region boxed in red, and all our 22 reads are aligned to both sides of the repeat. Do you have any guesses? 
![repeat](https://user-images.githubusercontent.com/19406763/58483193-2939ad00-8160-11e9-9e2c-29ce4b80e0d7.png)
Thank you,
Simone

**Comment by arnederoeck** [comment]
Thank you for attaching the figure. I think the problem will be the relatively short overlap on the left flank. I assume these reads are amplicon based? In the `Spanning_read_extractor.sh` script, you could lower the number of the `extension` parameter on line 27. You could for instance go for `extension=250`. Smaller flanks could lead to problems downstream, however, as it can become more difficult for the algorithm to find it in the squiggles and therefore result in low quality tandem repeat segementation.

**Comment by MaestSi** [comment]
Dear arne,
the reads you saw in the image have been obtained sequencing a Cas9-enriched target, and they are extending to the left flank of the repeat for 120bp. I had to further lower down the extension value to 100, and at least all the 23 reads have been extracted. Hope this is not going to cause major issues downstream. Thank you very much for the support.
Simone
