### ISSUE TITLE
Positive/Negative strand differences

### ISSUE THREAD

**Issue by mattdmem** [arnederoeck/NanoSatellite#4]
Hello - Great tool!

Just wondering about differences we are seeing on the positive and negative strands and if you'd experiences something similar. We are sequencing plasmids which contain repeats of known lengths.

We have sequecned two plasmids, one, just using the positive strand gives us the expected size, and one just using the negative strand gives us the correct size. 

I've plotted here one of the QC plots with the strands coloured. Do you know hat could be causing the shift to the right we see from positive strands and how we might be able to fix this?

Could it be a problem with the flanking sequence?

![image](https://user-images.githubusercontent.com/16154750/49501344-8700d280-f86a-11e8-9313-1c76ae8f8141.png)

Thanks!

**Comment by arnederoeck** [comment]
Hi,
Thank you for your interest.
Short answer: The difference you see between strands is normal.

It's not because of the flanks, but it is caused by the tandem repeat squiggles themselves that can have a totally different "shape" depending on the strand (also in your graphs, you see the biggest difference between positive and negative strands is on the x-axis, which corresponds to the distance of segmenting the tandem repeat in different units).
So for instance, if one strand has a lot of high and low current signals, while the other has a more "flat" pattern, it will change the success of dynamic time warping (DTW) to recognize individual units which will affect the DTW distance (which is plotted in the graph).

I hope this explains it a bit.

Cheers!
