### ISSUE TITLE
Error in if (right_dist < left_dist) 

### ISSUE THREAD

**Issue by liutiming** [arnederoeck/NanoSatellite#5]
![image](https://user-images.githubusercontent.com/39947942/52112253-ea2b9d00-2640-11e9-8b04-c996a724f95d.png)
Hello. First thanks so much for publishing this wonderful programme!

While I am trying to use it by following the suggested workflow, I encountered an error (shown in the pic) at this step: 
Rscript Signal2chunk.R <spanning_reads file> <reference_squiggles.squiggle>

May I ask how I can resolve it, please? Please let me know if more info is needed. I have installed all the dependencies for NanoSatellite.

**Comment by arnederoeck** [comment]
Hi, thank you for your interest in NanoSatellite and for reporting this error.
Based on the info you supplied me, I am not really sure what is causing this error. Nevertheless I added a piece of code to the script, which should circumvent the presumed problem without affecting any other results. 
Let me know whether it works or not, so that I can take another look at it if needed.

Cheers!

**Comment by liutiming** [comment]
It works fine now. Thank you very much!
